import * as THREE from 'https://unpkg.com/three@0.180.0/build/three.module.js';
import {steer,nearest,offenseRoutePoint,smartBlocker,coverage} from './ai.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rand=(a,b)=>a+Math.random()*(b-a);
export class Game{
  constructor(canvas,career,ui){this.canvas=canvas;this.career=career;this.ui=ui;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x07111f);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.camera=new THREE.PerspectiveCamera(52,1,.1,500);this.camera.position.set(-18,23,26);this.clock3=new THREE.Clock();this.keys=new Set();this.players=[];this.offense=[];this.defense=[];this.ball=null;this.state='menu';this.selectedPlay='short';this.controlled=null;this.ballCarrier=null;this.targetIndex=0;this.homeScore=0;this.awayScore=0;this.quarter=1;this.gameClock=120;this.down=1;this.toGo=10;this.ballYard=25;this.firstDownYard=35;this.playTime=0;this.practice=false;this.pendingReset=0;this.setupWorld();this.bindInput();this.resize();addEventListener('resize',()=>this.resize())}
  setupWorld(){const hemi=new THREE.HemisphereLight(0xb8dbff,0x22331d,2.3);this.scene.add(hemi);const sun=new THREE.DirectionalLight(0xffffff,2.8);sun.position.set(-25,42,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);this.scene.add(sun);const field=new THREE.Mesh(new THREE.PlaneGeometry(120,53.3),new THREE.MeshStandardMaterial({color:0x176f39,roughness:.88}));field.rotation.x=-Math.PI/2;field.receiveShadow=true;field.position.x=10;this.scene.add(field);const endMat=new THREE.MeshStandardMaterial({color:0x0a4264});for(const x of [-45,65]){const e=new THREE.Mesh(new THREE.PlaneGeometry(10,53.3),endMat);e.rotation.x=-Math.PI/2;e.position.set(x,.012,0);this.scene.add(e)}const lineMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.78});for(let x=-40;x<=60;x+=5){const l=new THREE.Mesh(new THREE.PlaneGeometry(.09,52),lineMat);l.rotation.x=-Math.PI/2;l.position.set(x,.02,0);this.scene.add(l)}for(let z=-22;z<=22;z+=44){const s=new THREE.Mesh(new THREE.PlaneGeometry(110,.15),lineMat);s.rotation.x=-Math.PI/2;s.position.set(10,.025,z);this.scene.add(s)}this.buildStadium();this.buildBall()}
  buildStadium(){const mat=new THREE.MeshStandardMaterial({color:0x17283c,roughness:.95});for(const z of [-33,33])for(let i=0;i<6;i++){const s=new THREE.Mesh(new THREE.BoxGeometry(128,2.6,3.4),mat);s.position.set(10,1.4+i*1.8,z+Math.sign(z)*i*2.2);this.scene.add(s)}for(const x of [-54,74]){const s=new THREE.Mesh(new THREE.BoxGeometry(4,11,66),mat);s.position.set(x,5,0);this.scene.add(s)}}
  buildBall(){const g=new THREE.SphereGeometry(.38,18,12);g.scale(1.45,.75,.75);this.ball=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x7a3519,roughness:.75}));this.ball.castShadow=true;this.ball.visible=false;this.scene.add(this.ball);this.ballVel=new THREE.Vector3();this.ballTarget=null;this.ballThrown=false}
  bindInput(){addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;this.keys.add(e.code);if(e.code==='Space'&&this.state==='presnap')this.snap();if(e.code==='KeyQ'&&this.state==='live')this.cycleTarget(-1);if(e.code==='KeyE'&&this.state==='live')this.cycleTarget(1);if(e.code==='KeyR'&&this.state==='live'&&this.ballCarrier)this.juke()});addEventListener('keyup',e=>this.keys.delete(e.code));this.canvas.addEventListener('pointerdown',e=>{if(this.state!=='live'||!this.ballCarrier||this.ballCarrier.role!=='QB'||this.ballThrown)return;const r=this.canvas.getBoundingClientRect();const m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(m,this.camera);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);const hit=new THREE.Vector3();if(ray.ray.intersectPlane(plane,hit))this.throwBall(hit)})}
  resize(){const w=this.canvas.clientWidth||innerWidth,h=this.canvas.clientHeight||innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  makePlayer(team,role,pos,z,stats={}){const group=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.52,1.05,5,8),new THREE.MeshStandardMaterial({color:team==='offense'?0xffcc33:0xe74c5b,roughness:.72}));body.castShadow=true;body.position.y=1;group.add(body);const helmet=new THREE.Mesh(new THREE.SphereGeometry(.55,14,10),new THREE.MeshStandardMaterial({color:team==='offense'?0x112d55:0xf4f4f4,roughness:.55,metalness:.1}));helmet.position.y=2;helmet.castShadow=true;group.add(helmet);group.position.set(pos,0,z);this.scene.add(group);const p={id:`${team[0]}${this.players.length}`,team,role,group,body,velocity:new THREE.Vector3(),active:true,eligible:['WR','TE','RB'].includes(role),route:'go',routeStart:group.position.clone(),lane:z,blockTarget:null,stats:{speed:stats.speed||70,strength:stats.strength||70,skill:stats.skill||70,stamina:stats.stamina||70},stamina:100};this.players.push(p);(team==='offense'?this.offense:this.defense).push(p);return p}
  clearPlayers(){for(const p of this.players)this.scene.remove(p.group);this.players=[];this.offense=[];this.defense=[]}
  buildFormation(play){this.clearPlayers();const roster=this.career.data.roster;const byPos=pos=>roster.find(p=>p.pos===pos)||roster[0];const q=this.makePlayer('offense','QB',-8,0,byPos('QB'));q.eligible=false;const rb=this.makePlayer('offense','RB',-10,-4,byPos('RB'));const wrs=roster.filter(p=>p.pos==='WR');const wr1=this.makePlayer('offense','WR',-6,-18,wrs[0]||byPos('WR'));const wr2=this.makePlayer('offense','WR',-6,18,wrs[1]||byPos('WR'));const te=this.makePlayer('offense','TE',-6,10,byPos('TE'));for(const z of [-6,-3,0,3,6]){const ol=this.makePlayer('offense','OL',-5,z,byPos('OL'));ol.eligible=false}const routes={short:['slant','out','curl','flat'],deep:['go','go','slant','go'],screen:['go','go','out','flat'],run:['go','slant','out','flat']}[play]||['slant','out','curl','flat'];[wr1,wr2,te,rb].forEach((p,i)=>p.route=routes[i]);for(const z of [-18,-12,-6,0,6,12,18])this.makePlayer('defense',z===0?'LB':'DB',1,z,{speed:72+rand(-5,7),strength:70+rand(-5,7),skill:72,stamina:80});for(const z of [-5,0,5])this.makePlayer('defense','DL',-1,z,{speed:62,strength:82,skill:70,stamina:85});this.controlled=q;this.ballCarrier=q;this.targetIndex=0;this.ball.visible=true;this.ballThrown=false;this.ballTarget=null;this.updateBallHeld()}
  start(practice=false){this.practice=practice;this.homeScore=0;this.awayScore=0;this.quarter=1;this.gameClock=practice?999:120;this.down=1;this.toGo=10;this.ballYard=25;this.firstDownYard=35;this.state='playcall';this.ui.showGame();this.ui.showPlayCall(true);this.ui.update(this)}
  choosePlay(play){if(play==='fieldGoal'){this.fieldGoal();return}if(play==='punt'){this.punt();return}this.selectedPlay=play;this.buildFormation(play);this.state='presnap';this.ui.showPlayCall(false);this.ui.setHint(play==='run'?'SPACE snap · WASD run · R juke':'SPACE snap · click field to throw · Q/E change receiver');this.updateCamera(true)}
  snap(){if(this.state!=='presnap')return;this.state='live';this.playTime=0;for(const p of this.players){p.routeStart=p.group.position.clone();p.blockTarget=null}if(this.selectedPlay==='run'){const rb=this.offense.find(p=>p.role==='RB');this.ballCarrier=rb;this.controlled=rb;rb.group.position.set(-7,0,-1);this.ui.setHint('WASD run · R juke · find the lane')}else this.ui.setHint('Click ahead of a receiver to throw · Q/E changes target')}
  cycleTarget(dir){const eligible=this.offense.filter(p=>p.eligible&&p.active);if(!eligible.length)return;this.targetIndex=(this.targetIndex+dir+eligible.length)%eligible.length;this.ui.target(eligible[this.targetIndex].role)}
  throwBall(point){if(!this.ballCarrier||this.ballCarrier.role!=='QB')return;this.ballThrown=true;this.ballCarrier=null;this.controlled=null;this.ballTarget=point.clone();const from=this.ball.position.clone();const dist=from.distanceTo(point);const t=clamp(dist/25,.65,1.65);this.ballVel.copy(point).sub(from).divideScalar(t);this.ballVel.y=8+dist*.16;this.ui.setHint('Ball in the air…')}
  juke(){if(!this.controlled||this.controlled.jukeCd>0)return;this.controlled.jukeCd=.8;this.controlled.velocity.z+=Math.random()>.5?7:-7}
  updateInput(dt){const p=this.controlled;if(!p||this.state!=='live')return;let x=0,z=0;if(this.keys.has('KeyW')||this.keys.has('ArrowUp'))x+=1;if(this.keys.has('KeyS')||this.keys.has('ArrowDown'))x-=1;if(this.keys.has('KeyA')||this.keys.has('ArrowLeft'))z-=1;if(this.keys.has('KeyD')||this.keys.has('ArrowRight'))z+=1;const v=new THREE.Vector3(x,0,z);if(v.lengthSq()){v.normalize();const sprint=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight');const max=(6.4+p.stats.speed/100*4.8)*(sprint?1.12:1);p.velocity.lerp(v.multiplyScalar(max),Math.min(1,dt*12));p.stamina=clamp(p.stamina-dt*(sprint?14:5),0,100)}else p.stamina=clamp(p.stamina+dt*8,0,100)}
  updateAI(dt){const carrier=this.ballCarrier;for(const p of this.offense){if(!p.active||p===this.controlled)continue;if(this.state==='presnap'){p.velocity.multiplyScalar(.7);continue}if(p.role==='OL'||(!p.eligible&&p.role!=='QB')){if(carrier)smartBlocker(p,carrier,this.defense,this.offense,dt);continue}if(carrier&&carrier.role!=='QB'){smartBlocker(p,carrier,this.defense,this.offense,dt);continue}const target=offenseRoutePoint(p,this.playTime);steer(p,target,6.7+p.stats.speed/100*3,dt,7)}for(const d of this.defense){if(!d.active)continue;coverage(d,this.offense,carrier,dt)}}
  resolveBlocks(dt){for(const o of this.offense){if(!o.active)continue;for(const d of this.defense){if(!d.active)continue;const dist=o.group.position.distanceTo(d.group.position);if(dist<1.28&&o!==this.ballCarrier){const power=(o.stats.strength-d.stats.strength)/100;d.velocity.x-=dt*(5+power*5);d.velocity.z+=(d.group.position.z-o.group.position.z)*dt*2.2}}}}
  updatePlayers(dt){for(const p of this.players){p.jukeCd=Math.max(0,(p.jukeCd||0)-dt);p.group.position.addScaledVector(p.velocity,dt);p.velocity.multiplyScalar(Math.pow(.06,dt));p.group.position.z=clamp(p.group.position.z,-25.2,25.2);p.group.position.x=clamp(p.group.position.x,-48,68);if(p.velocity.lengthSq()>.2)p.group.rotation.y=Math.atan2(p.velocity.z,p.velocity.x)-Math.PI/2}}
  updateBall(dt){if(this.ballCarrier){this.updateBallHeld();return}if(!this.ballThrown)return;this.ballVel.y-=18*dt;this.ball.position.addScaledVector(this.ballVel,dt);this.ball.rotation.z+=dt*12;let catcher=null,best=1.4;for(const p of this.players){if(!p.active)continue;if(p.team==='offense'&&!p.eligible)continue;const d=p.group.position.clone().add(new THREE.Vector3(0,1.5,0)).distanceTo(this.ball.position);if(d<best){best=d;catcher=p}}if(catcher){const offense=catcher.team==='offense';const chance=offense?.58+catcher.stats.skill/240:.45;if(Math.random()<chance){this.ballCarrier=catcher;this.controlled=offense?catcher:null;this.ballThrown=false;this.ui.setHint(offense?'Caught! WASD run · R juke':'Intercepted!');if(!offense)setTimeout(()=>this.turnover('Interception'),500);return}}if(this.ball.position.y<=.3){this.ball.position.y=.3;this.ballThrown=false;this.endPlay('Incomplete',0,false)}}
  updateBallHeld(){if(!this.ballCarrier)return;this.ball.position.copy(this.ballCarrier.group.position).add(new THREE.Vector3(.1,1.35,.25));this.ball.rotation.z=.4}
  detectTackles(){const c=this.ballCarrier;if(!c||c.team!=='offense'||this.state!=='live')return;for(const d of this.defense){if(!d.active)continue;const dist=c.group.position.distanceTo(d.group.position);if(dist<1.18){const juke=(c.jukeCd||0)>.52;const odds=juke?.16:.72;const strength=(d.stats.strength-c.stats.strength)/240;if(Math.random()<clamp(odds+strength,.08,.92)){const gained=c.group.position.x+8;this.endPlay('Tackled',gained,true);return}else{d.velocity.x-=4;d.velocity.z+=rand(-3,3)}}}}
  detectScore(){const c=this.ballCarrier;if(c&&c.team==='offense'&&c.group.position.x>=60){this.homeScore+=7;this.toast('TOUCHDOWN +7');this.resetDriveAfterScore();return true}return false}
  endPlay(reason,relativeX,counts=true){if(this.state!=='live')return;this.state='dead';const gained=counts?Math.max(-10,relativeX):0;this.ballYard=clamp(this.ballYard+gained,1,99);if(counts){this.toGo-=gained;if(this.toGo<=0){this.down=1;this.firstDownYard=Math.min(100,this.ballYard+10);this.toGo=Math.max(1,this.firstDownYard-this.ballYard);this.toast(`FIRST DOWN · +${Math.round(gained)} yd`)}else{this.down++;if(this.down>4){this.turnover('Turnover on downs');return}else this.toast(`${reason} · ${gained>=0?'+':''}${Math.round(gained)} yd`)}}else this.toast(reason);this.pendingReset=.85}
  resetPlay(){if(this.state!=='dead')return;this.state='playcall';this.ball.visible=false;this.clearPlayers();this.ui.showPlayCall(true);this.ui.update(this)}
  turnover(reason){if(this.state==='transition')return;this.state='transition';this.toast(reason);this.ball.visible=false;this.clearPlayers();setTimeout(()=>this.simulateCpuDrive(),700)}
  simulateCpuDrive(){const team=this.career.teamStars();const defenseRating=clamp(team,1,10);const cpu=5.5+Math.min(this.quarter,4)*.25;const touchdownChance=clamp(.55-(defenseRating-cpu)*.045,.18,.72);if(Math.random()<touchdownChance)this.awayScore+=7;else if(Math.random()<.22)this.awayScore+=3;this.gameClock=Math.max(0,this.gameClock-rand(18,42));this.down=1;this.ballYard=25;this.firstDownYard=35;this.toGo=10;this.state='playcall';this.ui.showPlayCall(true);this.ui.update(this);this.checkQuarter()}
  resetDriveAfterScore(){this.state='transition';this.ball.visible=false;this.clearPlayers();setTimeout(()=>this.simulateCpuDrive(),800)}
  fieldGoal(){const distance=Math.round(117-this.ballYard);const kicker=this.career.data.roster.find(p=>p.pos==='K');const rating=kicker?this.career.overall(kicker):60;const max=42+rating*.28;if(distance>max+12){this.toast('Too far for your kicker');return}const chance=clamp(.97-Math.max(0,distance-max)*.035,.2,.98);if(Math.random()<chance){this.homeScore+=3;this.toast(`FIELD GOAL · ${distance} yd`);this.resetDriveAfterScore()}else{this.toast('FIELD GOAL MISSED');this.turnover('Missed field goal')}}
  punt(){this.toast('Punt · field flipped');this.gameClock=Math.max(0,this.gameClock-8);this.turnover('Punt')}
  checkQuarter(){if(this.practice)return;if(this.gameClock>0)return;if(this.quarter>=4){this.finishGame();return}this.quarter++;this.gameClock=120;this.toast(`START Q${this.quarter}`)}
  finishGame(){this.state='gameover';const win=this.homeScore>=this.awayScore;if(!this.practice)this.career.recordGame(win);this.toast(win?'YOU WIN!':'GAME OVER');setTimeout(()=>this.ui.showGameOver(win,this),500)}
  toast(msg){this.ui.toast(msg)}
  updateCamera(force=false){let target;if(this.controlled)target=this.controlled.group.position;else if(this.ballThrown)target=this.ball.position;else target=new THREE.Vector3(-4,0,0);const desired=new THREE.Vector3(target.x-14,16,target.z+18);if(force)this.camera.position.copy(desired);else this.camera.position.lerp(desired,.08);this.camera.lookAt(target.x+5,1,target.z)}
  tick(){const dt=Math.min(this.clock3.getDelta(),.033);if(this.state==='live'){this.playTime+=dt;if(!this.practice){this.gameClock=Math.max(0,this.gameClock-dt);if(this.gameClock===0)this.checkQuarter()}this.updateInput(dt);this.updateAI(dt);this.resolveBlocks(dt);this.updatePlayers(dt);this.updateBall(dt);if(!this.detectScore())this.detectTackles();if(this.ballCarrier&&Math.abs(this.ballCarrier.group.position.z)>24.8){const gained=this.ballCarrier.group.position.x+8;this.endPlay('Out of bounds',gained,true)}this.ui.update(this)}if(this.pendingReset>0){this.pendingReset-=dt;if(this.pendingReset<=0)this.resetPlay()}this.updateCamera();this.renderer.render(this.scene,this.camera);requestAnimationFrame(()=>this.tick())}
}
