const $=id=>document.getElementById(id);const ord=n=>n===1?'1st':n===2?'2nd':n===3?'3rd':'4th';
export class UI{
  constructor(career){this.career=career;this.menu=$('menu');this.hud=$('hud');this.playCall=$('playCall');this.pause=$('pausePanel');this.careerPanel=$('careerPanel');this.toastEl=$('toast');this.toastTimer=0}
  showGame(){this.menu.classList.add('hidden');this.careerPanel.classList.add('hidden');this.hud.classList.remove('hidden')}
  showMenu(){this.hud.classList.add('hidden');this.playCall.classList.add('hidden');this.pause.classList.add('hidden');this.careerPanel.classList.add('hidden');this.menu.classList.remove('hidden')}
  showPlayCall(v){this.playCall.classList.toggle('hidden',!v)}
  setHint(s){$('hint').textContent=s}
  target(s){$('targetBadge').textContent=`Target: ${s}`}
  update(g){$('homeScore').textContent=g.homeScore;$('awayScore').textContent=g.awayScore;$('quarter').textContent=g.practice?'PRACTICE':`Q${g.quarter}`;$('clock').textContent=g.practice?'∞':`${Math.floor(g.gameClock/60)}:${String(Math.floor(g.gameClock%60)).padStart(2,'0')}`;$('downText').textContent=`${ord(g.down)} & ${Math.max(1,Math.ceil(g.toGo))}`;$('driveInfo').textContent=`Ball on ${Math.round(g.ballYard)} · ${g.selectedPlay||''}`;const dist=Math.round(117-g.ballYard);$('fgDistance').textContent=`${dist} yd`;const eligible=g.offense?.filter(p=>p.eligible&&p.active)||[];if(eligible.length)$('targetBadge').textContent=`Target: ${eligible[g.targetIndex%eligible.length].role}`}
  toast(msg){clearTimeout(this.toastTimer);this.toastEl.textContent=msg;this.toastEl.classList.remove('hidden');this.toastTimer=setTimeout(()=>this.toastEl.classList.add('hidden'),1900)}
  renderCareer(){const d=this.career.data;$('teamName').textContent=d.team;$('seasonText').textContent=d.season;$('recordText').textContent=`${d.wins}-${d.losses}`;$('creditsText').textContent=d.credits;const stars=this.career.teamStars();$('starsText').textContent='★'.repeat(Math.min(5,stars))+(stars>5?'\n'+'★'.repeat(stars-5):'')+'☆'.repeat(Math.max(0,5-Math.min(5,stars)));const list=$('rosterList');list.innerHTML='';for(const p of d.roster){const overall=this.career.overall(p);const card=document.createElement('div');card.className='player-card';card.innerHTML=`<div class="pos">${p.pos}</div><div><strong>${p.name}</strong><small> Lv.${p.level}${p.rebirths?` · Rebirth ${p.rebirths}`:''} · ${overall} OVR</small><div class="meter"><i style="width:${p.level}%"></i></div></div><div class="player-actions"></div>`;const actions=card.querySelector('.player-actions');if(p.level>=100){const b=document.createElement('button');b.textContent='Rebirth';b.addEventListener('click',()=>{this.career.rebirth(p.id);this.renderCareer();this.toast(`${p.name} reborn`)});actions.appendChild(b)}list.appendChild(card)}const fl=$('facilityList');fl.innerHTML='';for(const [name,lvl] of Object.entries(d.facilities)){const row=document.createElement('div');row.className='facility';const cost=lvl+1;row.innerHTML=`<span><strong>${name[0].toUpperCase()+name.slice(1)}</strong><br><small>Level ${lvl}/10</small></span>`;const b=document.createElement('button');b.textContent=lvl>=10?'MAX':`Upgrade · ${cost} CC`;b.disabled=lvl>=10;b.addEventListener('click',()=>{if(this.career.upgradeFacility(name)){this.renderCareer();this.toast(`${name} upgraded`)}else this.toast('Not enough credits')});row.appendChild(b);fl.appendChild(row)}}
  showCareer(){this.menu.classList.add('hidden');this.renderCareer();this.careerPanel.classList.remove('hidden')}
  showGameOver(win,g){this.playCall.classList.add('hidden');this.setHint(`${win?'WIN':'LOSS'} ${g.homeScore}-${g.awayScore} · Career saved · press Main Menu`);this.toast('Career progress saved')}
}
